spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventflow
    username: eventflow
    password: eventflow1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  jackson:
    time-zone: Asia/Seoul
