-- 기존 ddl-auto 로 생성되던 스키마의 baseline 스냅샷
-- 이후 스키마 변경은 V2 부터 마이그레이션 파일로 관리

create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    name varchar(100) not null,
    created_at timestamp(6),
    updated_at timestamp(6)
);

create table events (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description text,
    location varchar(255),
    status varchar(20) not null,
    start_at timestamp(6) not null,
    end_at timestamp(6) not null,
    created_by bigint not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint events_status_check check (status in ('OPEN', 'CLOSED')),
    constraint fk_events_created_by foreign key (created_by) references users(id)
);

create table event_schedules (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    name varchar(100),
    start_at timestamp(6) not null,
    end_at timestamp(6) not null,
    sale_start_at timestamp(6) not null,
    sale_end_at timestamp(6) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint fk_event_schedules_event foreign key (event_id) references events(id)
);

create table seats (
    id bigint generated by default as identity primary key,
    event_schedule_id bigint not null,
    seat_number varchar(20) not null,
    grade varchar(10) not null,
    price integer not null,
    status varchar(20) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint seats_grade_check check (grade in ('VIP', 'R', 'S')),
    constraint seats_status_check check (status in ('AVAILABLE', 'RESERVED')),
    constraint uk_seat_schedule_number unique (event_schedule_id, seat_number),
    constraint fk_seats_event_schedule foreign key (event_schedule_id) references event_schedules(id)
);

create table reservations (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    seat_id bigint not null,
    price integer not null,
    status varchar(20) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint reservations_status_check check (status in ('PENDING', 'PAID', 'CANCELLED')),
    constraint fk_reservations_user foreign key (user_id) references users(id),
    constraint fk_reservations_seat foreign key (seat_id) references seats(id)
);

create table payments (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null unique,
    payment_key varchar(255),
    amount integer not null,
    status varchar(20) not null,
    paid_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint payments_status_check check (status in ('READY', 'SUCCESS', 'FAILED')),
    constraint fk_payments_reservation foreign key (reservation_id) references reservations(id)
);

create table tickets (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null,
    user_id bigint not null,
    event_id bigint not null,
    qr_token varchar(255) not null unique,
    status varchar(20) not null,
    issued_at timestamp(6),
    used_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint tickets_status_check check (status in ('ISSUED', 'USED', 'CANCELLED')),
    constraint fk_tickets_reservation foreign key (reservation_id) references reservations(id),
    constraint fk_tickets_user foreign key (user_id) references users(id),
    constraint fk_tickets_event foreign key (event_id) references events(id)
);

create table entry_logs (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    event_id bigint not null,
    result varchar(30) not null,
    checked_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint entry_logs_result_check check (result in ('SUCCESS', 'ALREADY_USED', 'INVALID')),
    constraint fk_entry_logs_ticket foreign key (ticket_id) references tickets(id),
    constraint fk_entry_logs_event foreign key (event_id) references events(id)
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(512) not null unique,
    expires_at timestamp(6) not null,
    created_at timestamp(6),
    updated_at timestamp(6)
);
